// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_dashboard.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminDashboardStats = `-- name: GetAdminDashboardStats :one
SELECT 
    (SELECT COUNT(*) FROM organizations) as total_organizations,
    (SELECT COUNT(*) FROM organizations WHERE status = 'ACTIVE') as active_organizations,
    (SELECT COUNT(*) FROM users) as total_users,
    (SELECT COUNT(*) FROM users WHERE status = 'ACTIVE') as active_users,
    (SELECT COUNT(*) FROM mind_maps) as total_mind_maps,
    (SELECT COUNT(*) FROM uploads WHERE status != 'FAILED') as total_uploads,
    (SELECT COALESCE(SUM(amount), 0)::bigint FROM ai_credit_transactions WHERE type = 'SUB') as credits_consumed,
    (SELECT COUNT(*) FROM subscriptions WHERE status IN ('ACTIVE', 'TRIALING')) as active_subscriptions,
    (SELECT COALESCE(SUM(amount), 0)::numeric FROM invoices WHERE status = 'PAID') as paid_invoices_amount
`

type GetAdminDashboardStatsRow struct {
	TotalOrganizations  int64
	ActiveOrganizations int64
	TotalUsers          int64
	ActiveUsers         int64
	TotalMindMaps       int64
	TotalUploads        int64
	CreditsConsumed     int64
	ActiveSubscriptions int64
	PaidInvoicesAmount  pgtype.Numeric
}

func (q *Queries) GetAdminDashboardStats(ctx context.Context) (GetAdminDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminDashboardStats)
	var i GetAdminDashboardStatsRow
	err := row.Scan(
		&i.TotalOrganizations,
		&i.ActiveOrganizations,
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.TotalMindMaps,
		&i.TotalUploads,
		&i.CreditsConsumed,
		&i.ActiveSubscriptions,
		&i.PaidInvoicesAmount,
	)
	return i, err
}
