// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    actor_user_id, organization_id, action, entity_type, entity_id, metadata, ip, user_agent
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, actor_user_id, organization_id, action, entity_type, entity_id, metadata, ip, user_agent, created_at
`

type CreateAuditLogParams struct {
	ActorUserID    pgtype.UUID
	OrganizationID pgtype.UUID
	Action         string
	EntityType     string
	EntityID       pgtype.UUID
	Metadata       []byte
	Ip             pgtype.Text
	UserAgent      pgtype.Text
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.OrganizationID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
		arg.Ip,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.OrganizationID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_user_id, organization_id, action, entity_type, entity_id, metadata, ip, user_agent, created_at
FROM audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.OrganizationID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsDetailed = `-- name: ListAuditLogsDetailed :many
SELECT al.id, al.actor_user_id, al.organization_id, al.action, al.entity_type, al.entity_id, al.metadata, al.ip, al.user_agent, al.created_at,
       u.email as actor_email, o.name as organization_name
FROM audit_logs al
LEFT JOIN users u ON al.actor_user_id = u.id
LEFT JOIN organizations o ON al.organization_id = o.id
ORDER BY al.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsDetailedParams struct {
	Limit  int32
	Offset int32
}

type ListAuditLogsDetailedRow struct {
	ID               pgtype.UUID
	ActorUserID      pgtype.UUID
	OrganizationID   pgtype.UUID
	Action           string
	EntityType       string
	EntityID         pgtype.UUID
	Metadata         []byte
	Ip               pgtype.Text
	UserAgent        pgtype.Text
	CreatedAt        pgtype.Timestamptz
	ActorEmail       pgtype.Text
	OrganizationName pgtype.Text
}

func (q *Queries) ListAuditLogsDetailed(ctx context.Context, arg ListAuditLogsDetailedParams) ([]ListAuditLogsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsDetailed, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsDetailedRow
	for rows.Next() {
		var i ListAuditLogsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.OrganizationID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ActorEmail,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
