// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoices
`

func (q *Queries) CountInvoices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvoicesByOrganization = `-- name: CountInvoicesByOrganization :one
SELECT COUNT(*) FROM invoices WHERE organization_id = $1
`

func (q *Queries) CountInvoicesByOrganization(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoicesByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentTransactions = `-- name: CountPaymentTransactions :one
SELECT COUNT(*) FROM payment_transactions
`

func (q *Queries) CountPaymentTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebhookEvents = `-- name: CountWebhookEvents :one
SELECT COUNT(*) FROM webhook_events
`

func (q *Queries) CountWebhookEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    organization_id, subscription_id, amount, currency, status, external_invoice_id, pdf_url, due_date, billing_type, invoice_url, bank_slip_url, pix_qr_code, pix_copy_paste
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, organization_id, subscription_id, amount, currency, status, external_invoice_id, pdf_url, due_date, billing_type, invoice_url, bank_slip_url, pix_qr_code, pix_copy_paste, paid_at, created_at, updated_at
`

type CreateInvoiceParams struct {
	OrganizationID    pgtype.UUID
	SubscriptionID    pgtype.UUID
	Amount            pgtype.Numeric
	Currency          string
	Status            string
	ExternalInvoiceID pgtype.Text
	PdfUrl            pgtype.Text
	DueDate           pgtype.Timestamptz
	BillingType       pgtype.Text
	InvoiceUrl        pgtype.Text
	BankSlipUrl       pgtype.Text
	PixQrCode         pgtype.Text
	PixCopyPaste      pgtype.Text
}

type CreateInvoiceRow struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	SubscriptionID    pgtype.UUID
	Amount            pgtype.Numeric
	Currency          string
	Status            string
	ExternalInvoiceID pgtype.Text
	PdfUrl            pgtype.Text
	DueDate           pgtype.Timestamptz
	BillingType       pgtype.Text
	InvoiceUrl        pgtype.Text
	BankSlipUrl       pgtype.Text
	PixQrCode         pgtype.Text
	PixCopyPaste      pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (CreateInvoiceRow, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.OrganizationID,
		arg.SubscriptionID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.ExternalInvoiceID,
		arg.PdfUrl,
		arg.DueDate,
		arg.BillingType,
		arg.InvoiceUrl,
		arg.BankSlipUrl,
		arg.PixQrCode,
		arg.PixCopyPaste,
	)
	var i CreateInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SubscriptionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalInvoiceID,
		&i.PdfUrl,
		&i.DueDate,
		&i.BillingType,
		&i.InvoiceUrl,
		&i.BankSlipUrl,
		&i.PixQrCode,
		&i.PixCopyPaste,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentCustomer = `-- name: CreatePaymentCustomer :one
INSERT INTO payment_customers (
    organization_id, provider, external_customer_id, name, email, document, phone, payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, provider, external_customer_id, name, email, document, phone, payload, created_at, updated_at
`

type CreatePaymentCustomerParams struct {
	OrganizationID     pgtype.UUID
	Provider           string
	ExternalCustomerID string
	Name               pgtype.Text
	Email              pgtype.Text
	Document           pgtype.Text
	Phone              pgtype.Text
	Payload            []byte
}

func (q *Queries) CreatePaymentCustomer(ctx context.Context, arg CreatePaymentCustomerParams) (PaymentCustomer, error) {
	row := q.db.QueryRow(ctx, createPaymentCustomer,
		arg.OrganizationID,
		arg.Provider,
		arg.ExternalCustomerID,
		arg.Name,
		arg.Email,
		arg.Document,
		arg.Phone,
		arg.Payload,
	)
	var i PaymentCustomer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ExternalCustomerID,
		&i.Name,
		&i.Email,
		&i.Document,
		&i.Phone,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentProvider = `-- name: CreatePaymentProvider :one
INSERT INTO payment_providers (
    name, slug, api_key_secure, webhook_secret_secure, is_active, mode
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, api_key_secure, webhook_secret_secure, is_active, mode, created_at
`

type CreatePaymentProviderParams struct {
	Name                string
	Slug                string
	ApiKeySecure        pgtype.Text
	WebhookSecretSecure pgtype.Text
	IsActive            bool
	Mode                string
}

type CreatePaymentProviderRow struct {
	ID                  pgtype.UUID
	Name                string
	Slug                string
	ApiKeySecure        pgtype.Text
	WebhookSecretSecure pgtype.Text
	IsActive            bool
	Mode                string
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) CreatePaymentProvider(ctx context.Context, arg CreatePaymentProviderParams) (CreatePaymentProviderRow, error) {
	row := q.db.QueryRow(ctx, createPaymentProvider,
		arg.Name,
		arg.Slug,
		arg.ApiKeySecure,
		arg.WebhookSecretSecure,
		arg.IsActive,
		arg.Mode,
	)
	var i CreatePaymentProviderRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.WebhookSecretSecure,
		&i.IsActive,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO payment_transactions (
    organization_id, invoice_id, amount, provider, external_transaction_id, status, payment_method, payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, invoice_id, amount, provider, external_transaction_id, status, payment_method, payload, created_at
`

type CreatePaymentTransactionParams struct {
	OrganizationID        pgtype.UUID
	InvoiceID             pgtype.UUID
	Amount                pgtype.Numeric
	Provider              string
	ExternalTransactionID pgtype.Text
	Status                string
	PaymentMethod         pgtype.Text
	Payload               []byte
}

type CreatePaymentTransactionRow struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	InvoiceID             pgtype.UUID
	Amount                pgtype.Numeric
	Provider              string
	ExternalTransactionID pgtype.Text
	Status                string
	PaymentMethod         pgtype.Text
	Payload               []byte
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (CreatePaymentTransactionRow, error) {
	row := q.db.QueryRow(ctx, createPaymentTransaction,
		arg.OrganizationID,
		arg.InvoiceID,
		arg.Amount,
		arg.Provider,
		arg.ExternalTransactionID,
		arg.Status,
		arg.PaymentMethod,
		arg.Payload,
	)
	var i CreatePaymentTransactionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.Amount,
		&i.Provider,
		&i.ExternalTransactionID,
		&i.Status,
		&i.PaymentMethod,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (
    provider, event_type, external_id, payload, status, error, processed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider, event_type, external_id, payload, status, error, processed_at, created_at
`

type CreateWebhookEventParams struct {
	Provider    string
	EventType   string
	ExternalID  string
	Payload     json.RawMessage
	Status      string
	Error       pgtype.Text
	ProcessedAt pgtype.Timestamptz
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.Provider,
		arg.EventType,
		arg.ExternalID,
		arg.Payload,
		arg.Status,
		arg.Error,
		arg.ProcessedAt,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventType,
		&i.ExternalID,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByExternalID = `-- name: GetInvoiceByExternalID :one
SELECT id, organization_id, subscription_id, amount, currency, status, external_invoice_id, pdf_url, due_date, billing_type, invoice_url, bank_slip_url, pix_qr_code, pix_copy_paste, paid_at, created_at, updated_at
FROM invoices
WHERE external_invoice_id = $1 LIMIT 1
`

type GetInvoiceByExternalIDRow struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	SubscriptionID    pgtype.UUID
	Amount            pgtype.Numeric
	Currency          string
	Status            string
	ExternalInvoiceID pgtype.Text
	PdfUrl            pgtype.Text
	DueDate           pgtype.Timestamptz
	BillingType       pgtype.Text
	InvoiceUrl        pgtype.Text
	BankSlipUrl       pgtype.Text
	PixQrCode         pgtype.Text
	PixCopyPaste      pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetInvoiceByExternalID(ctx context.Context, externalInvoiceID pgtype.Text) (GetInvoiceByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByExternalID, externalInvoiceID)
	var i GetInvoiceByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SubscriptionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalInvoiceID,
		&i.PdfUrl,
		&i.DueDate,
		&i.BillingType,
		&i.InvoiceUrl,
		&i.BankSlipUrl,
		&i.PixQrCode,
		&i.PixCopyPaste,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, organization_id, subscription_id, amount, currency, status, external_invoice_id, pdf_url, due_date, billing_type, invoice_url, bank_slip_url, pix_qr_code, pix_copy_paste, paid_at, created_at, updated_at
FROM invoices
WHERE id = $1 LIMIT 1
`

type GetInvoiceByIDRow struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	SubscriptionID    pgtype.UUID
	Amount            pgtype.Numeric
	Currency          string
	Status            string
	ExternalInvoiceID pgtype.Text
	PdfUrl            pgtype.Text
	DueDate           pgtype.Timestamptz
	BillingType       pgtype.Text
	InvoiceUrl        pgtype.Text
	BankSlipUrl       pgtype.Text
	PixQrCode         pgtype.Text
	PixCopyPaste      pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetInvoiceByID(ctx context.Context, id pgtype.UUID) (GetInvoiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i GetInvoiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SubscriptionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalInvoiceID,
		&i.PdfUrl,
		&i.DueDate,
		&i.BillingType,
		&i.InvoiceUrl,
		&i.BankSlipUrl,
		&i.PixQrCode,
		&i.PixCopyPaste,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentCustomer = `-- name: GetPaymentCustomer :one
SELECT id, organization_id, provider, external_customer_id, name, email, document, phone, payload, created_at, updated_at
FROM payment_customers
WHERE provider = $1 AND organization_id = $2 LIMIT 1
`

type GetPaymentCustomerParams struct {
	Provider       string
	OrganizationID pgtype.UUID
}

func (q *Queries) GetPaymentCustomer(ctx context.Context, arg GetPaymentCustomerParams) (PaymentCustomer, error) {
	row := q.db.QueryRow(ctx, getPaymentCustomer, arg.Provider, arg.OrganizationID)
	var i PaymentCustomer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ExternalCustomerID,
		&i.Name,
		&i.Email,
		&i.Document,
		&i.Phone,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentCustomerByExternalID = `-- name: GetPaymentCustomerByExternalID :one
SELECT id, organization_id, provider, external_customer_id, name, email, document, phone, payload, created_at, updated_at
FROM payment_customers
WHERE provider = $1 AND external_customer_id = $2 LIMIT 1
`

type GetPaymentCustomerByExternalIDParams struct {
	Provider           string
	ExternalCustomerID string
}

func (q *Queries) GetPaymentCustomerByExternalID(ctx context.Context, arg GetPaymentCustomerByExternalIDParams) (PaymentCustomer, error) {
	row := q.db.QueryRow(ctx, getPaymentCustomerByExternalID, arg.Provider, arg.ExternalCustomerID)
	var i PaymentCustomer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.ExternalCustomerID,
		&i.Name,
		&i.Email,
		&i.Document,
		&i.Phone,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentProviderBySlug = `-- name: GetPaymentProviderBySlug :one
SELECT id, name, slug, api_key_secure, webhook_secret_secure, is_active, mode, created_at
FROM payment_providers
WHERE slug = $1 LIMIT 1
`

type GetPaymentProviderBySlugRow struct {
	ID                  pgtype.UUID
	Name                string
	Slug                string
	ApiKeySecure        pgtype.Text
	WebhookSecretSecure pgtype.Text
	IsActive            bool
	Mode                string
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) GetPaymentProviderBySlug(ctx context.Context, slug string) (GetPaymentProviderBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPaymentProviderBySlug, slug)
	var i GetPaymentProviderBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.WebhookSecretSecure,
		&i.IsActive,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentTransactionByExternalID = `-- name: GetPaymentTransactionByExternalID :one
SELECT id, organization_id, invoice_id, amount, provider, external_transaction_id, status, payment_method, payload, created_at
FROM payment_transactions
WHERE external_transaction_id = $1 LIMIT 1
`

type GetPaymentTransactionByExternalIDRow struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	InvoiceID             pgtype.UUID
	Amount                pgtype.Numeric
	Provider              string
	ExternalTransactionID pgtype.Text
	Status                string
	PaymentMethod         pgtype.Text
	Payload               []byte
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetPaymentTransactionByExternalID(ctx context.Context, externalTransactionID pgtype.Text) (GetPaymentTransactionByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentTransactionByExternalID, externalTransactionID)
	var i GetPaymentTransactionByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.Amount,
		&i.Provider,
		&i.ExternalTransactionID,
		&i.Status,
		&i.PaymentMethod,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEventByExternalID = `-- name: GetWebhookEventByExternalID :one
SELECT id, provider, event_type, external_id, payload, status, error, processed_at, created_at
FROM webhook_events
WHERE provider = $1 AND external_id = $2 LIMIT 1
`

type GetWebhookEventByExternalIDParams struct {
	Provider   string
	ExternalID string
}

func (q *Queries) GetWebhookEventByExternalID(ctx context.Context, arg GetWebhookEventByExternalIDParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByExternalID, arg.Provider, arg.ExternalID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventType,
		&i.ExternalID,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoicesByOrganization = `-- name: ListInvoicesByOrganization :many
SELECT id, organization_id, subscription_id, amount, currency, status, external_invoice_id, pdf_url, due_date, billing_type, invoice_url, bank_slip_url, pix_qr_code, pix_copy_paste, paid_at, created_at
FROM invoices
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesByOrganizationParams struct {
	OrganizationID pgtype.UUID
	Limit          int32
	Offset         int32
}

type ListInvoicesByOrganizationRow struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	SubscriptionID    pgtype.UUID
	Amount            pgtype.Numeric
	Currency          string
	Status            string
	ExternalInvoiceID pgtype.Text
	PdfUrl            pgtype.Text
	DueDate           pgtype.Timestamptz
	BillingType       pgtype.Text
	InvoiceUrl        pgtype.Text
	BankSlipUrl       pgtype.Text
	PixQrCode         pgtype.Text
	PixCopyPaste      pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ListInvoicesByOrganization(ctx context.Context, arg ListInvoicesByOrganizationParams) ([]ListInvoicesByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesByOrganizationRow
	for rows.Next() {
		var i ListInvoicesByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SubscriptionID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.ExternalInvoiceID,
			&i.PdfUrl,
			&i.DueDate,
			&i.BillingType,
			&i.InvoiceUrl,
			&i.BankSlipUrl,
			&i.PixQrCode,
			&i.PixCopyPaste,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesDetailed = `-- name: ListInvoicesDetailed :many
SELECT i.id, i.organization_id, i.subscription_id, i.amount, i.currency, i.status, i.external_invoice_id, i.due_date, i.billing_type, i.invoice_url, i.paid_at, i.created_at,
       o.name as organization_name
FROM invoices i
JOIN organizations o ON i.organization_id = o.id
ORDER BY i.created_at DESC
LIMIT $1 OFFSET $2
`

type ListInvoicesDetailedParams struct {
	Limit  int32
	Offset int32
}

type ListInvoicesDetailedRow struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	SubscriptionID    pgtype.UUID
	Amount            pgtype.Numeric
	Currency          string
	Status            string
	ExternalInvoiceID pgtype.Text
	DueDate           pgtype.Timestamptz
	BillingType       pgtype.Text
	InvoiceUrl        pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	OrganizationName  string
}

func (q *Queries) ListInvoicesDetailed(ctx context.Context, arg ListInvoicesDetailedParams) ([]ListInvoicesDetailedRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesDetailed, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesDetailedRow
	for rows.Next() {
		var i ListInvoicesDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SubscriptionID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.ExternalInvoiceID,
			&i.DueDate,
			&i.BillingType,
			&i.InvoiceUrl,
			&i.PaidAt,
			&i.CreatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentProviders = `-- name: ListPaymentProviders :many
SELECT id, name, slug, api_key_secure, webhook_secret_secure, is_active, mode, created_at
FROM payment_providers
ORDER BY name ASC
`

type ListPaymentProvidersRow struct {
	ID                  pgtype.UUID
	Name                string
	Slug                string
	ApiKeySecure        pgtype.Text
	WebhookSecretSecure pgtype.Text
	IsActive            bool
	Mode                string
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) ListPaymentProviders(ctx context.Context) ([]ListPaymentProvidersRow, error) {
	rows, err := q.db.Query(ctx, listPaymentProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentProvidersRow
	for rows.Next() {
		var i ListPaymentProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ApiKeySecure,
			&i.WebhookSecretSecure,
			&i.IsActive,
			&i.Mode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTransactions = `-- name: ListPaymentTransactions :many
SELECT t.id, t.organization_id, t.invoice_id, t.amount, t.provider, t.external_transaction_id, t.status, t.payment_method, t.created_at,
       o.name as organization_name
FROM payment_transactions t
JOIN organizations o ON t.organization_id = o.id
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPaymentTransactionsParams struct {
	Limit  int32
	Offset int32
}

type ListPaymentTransactionsRow struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	InvoiceID             pgtype.UUID
	Amount                pgtype.Numeric
	Provider              string
	ExternalTransactionID pgtype.Text
	Status                string
	PaymentMethod         pgtype.Text
	CreatedAt             pgtype.Timestamptz
	OrganizationName      string
}

func (q *Queries) ListPaymentTransactions(ctx context.Context, arg ListPaymentTransactionsParams) ([]ListPaymentTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentTransactionsRow
	for rows.Next() {
		var i ListPaymentTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvoiceID,
			&i.Amount,
			&i.Provider,
			&i.ExternalTransactionID,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEvents = `-- name: ListWebhookEvents :many
SELECT id, provider, event_type, external_id, status, error, processed_at, created_at
FROM webhook_events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWebhookEventsParams struct {
	Limit  int32
	Offset int32
}

type ListWebhookEventsRow struct {
	ID          pgtype.UUID
	Provider    string
	EventType   string
	ExternalID  string
	Status      string
	Error       pgtype.Text
	ProcessedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListWebhookEvents(ctx context.Context, arg ListWebhookEventsParams) ([]ListWebhookEventsRow, error) {
	rows, err := q.db.Query(ctx, listWebhookEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookEventsRow
	for rows.Next() {
		var i ListWebhookEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.EventType,
			&i.ExternalID,
			&i.Status,
			&i.Error,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceDetails = `-- name: UpdateInvoiceDetails :one
UPDATE invoices
SET status = COALESCE($2, status),
    pdf_url = COALESCE($3, pdf_url),
    due_date = COALESCE($4, due_date),
    billing_type = COALESCE($5, billing_type),
    invoice_url = COALESCE($6, invoice_url),
    bank_slip_url = COALESCE($7, bank_slip_url),
    pix_qr_code = COALESCE($8, pix_qr_code),
    pix_copy_paste = COALESCE($9, pix_copy_paste),
    paid_at = COALESCE($10, paid_at),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, subscription_id, amount, currency, status, external_invoice_id, pdf_url, due_date, billing_type, invoice_url, bank_slip_url, pix_qr_code, pix_copy_paste, paid_at, created_at, updated_at
`

type UpdateInvoiceDetailsParams struct {
	ID           pgtype.UUID
	Status       string
	PdfUrl       pgtype.Text
	DueDate      pgtype.Timestamptz
	BillingType  pgtype.Text
	InvoiceUrl   pgtype.Text
	BankSlipUrl  pgtype.Text
	PixQrCode    pgtype.Text
	PixCopyPaste pgtype.Text
	PaidAt       pgtype.Timestamptz
}

type UpdateInvoiceDetailsRow struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	SubscriptionID    pgtype.UUID
	Amount            pgtype.Numeric
	Currency          string
	Status            string
	ExternalInvoiceID pgtype.Text
	PdfUrl            pgtype.Text
	DueDate           pgtype.Timestamptz
	BillingType       pgtype.Text
	InvoiceUrl        pgtype.Text
	BankSlipUrl       pgtype.Text
	PixQrCode         pgtype.Text
	PixCopyPaste      pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) UpdateInvoiceDetails(ctx context.Context, arg UpdateInvoiceDetailsParams) (UpdateInvoiceDetailsRow, error) {
	row := q.db.QueryRow(ctx, updateInvoiceDetails,
		arg.ID,
		arg.Status,
		arg.PdfUrl,
		arg.DueDate,
		arg.BillingType,
		arg.InvoiceUrl,
		arg.BankSlipUrl,
		arg.PixQrCode,
		arg.PixCopyPaste,
		arg.PaidAt,
	)
	var i UpdateInvoiceDetailsRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SubscriptionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalInvoiceID,
		&i.PdfUrl,
		&i.DueDate,
		&i.BillingType,
		&i.InvoiceUrl,
		&i.BankSlipUrl,
		&i.PixQrCode,
		&i.PixCopyPaste,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices
SET status = $2,
    paid_at = CASE WHEN $2 = 'PAID' THEN NOW() ELSE paid_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, subscription_id, amount, currency, status, external_invoice_id, pdf_url, due_date, billing_type, invoice_url, bank_slip_url, pix_qr_code, pix_copy_paste, paid_at, created_at, updated_at
`

type UpdateInvoiceStatusParams struct {
	ID     pgtype.UUID
	Status string
}

type UpdateInvoiceStatusRow struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	SubscriptionID    pgtype.UUID
	Amount            pgtype.Numeric
	Currency          string
	Status            string
	ExternalInvoiceID pgtype.Text
	PdfUrl            pgtype.Text
	DueDate           pgtype.Timestamptz
	BillingType       pgtype.Text
	InvoiceUrl        pgtype.Text
	BankSlipUrl       pgtype.Text
	PixQrCode         pgtype.Text
	PixCopyPaste      pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (UpdateInvoiceStatusRow, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	var i UpdateInvoiceStatusRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SubscriptionID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ExternalInvoiceID,
		&i.PdfUrl,
		&i.DueDate,
		&i.BillingType,
		&i.InvoiceUrl,
		&i.BankSlipUrl,
		&i.PixQrCode,
		&i.PixCopyPaste,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentProvider = `-- name: UpdatePaymentProvider :one
UPDATE payment_providers
SET api_key_secure = COALESCE($2, api_key_secure),
    webhook_secret_secure = COALESCE($3, webhook_secret_secure),
    is_active = COALESCE($4, is_active),
    mode = COALESCE($5, mode)
WHERE id = $1
RETURNING id, name, slug, api_key_secure, webhook_secret_secure, is_active, mode, created_at
`

type UpdatePaymentProviderParams struct {
	ID                  pgtype.UUID
	ApiKeySecure        pgtype.Text
	WebhookSecretSecure pgtype.Text
	IsActive            bool
	Mode                string
}

type UpdatePaymentProviderRow struct {
	ID                  pgtype.UUID
	Name                string
	Slug                string
	ApiKeySecure        pgtype.Text
	WebhookSecretSecure pgtype.Text
	IsActive            bool
	Mode                string
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) UpdatePaymentProvider(ctx context.Context, arg UpdatePaymentProviderParams) (UpdatePaymentProviderRow, error) {
	row := q.db.QueryRow(ctx, updatePaymentProvider,
		arg.ID,
		arg.ApiKeySecure,
		arg.WebhookSecretSecure,
		arg.IsActive,
		arg.Mode,
	)
	var i UpdatePaymentProviderRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.WebhookSecretSecure,
		&i.IsActive,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const updatePaymentTransactionStatus = `-- name: UpdatePaymentTransactionStatus :one
UPDATE payment_transactions
SET status = $2,
    paid_at = CASE WHEN $2 = 'PAID' THEN NOW() ELSE paid_at END,
    failed_at = CASE WHEN $2 = 'FAILED' THEN NOW() ELSE failed_at END
WHERE id = $1
RETURNING id, organization_id, invoice_id, amount, provider, external_transaction_id, status, payment_method, payload, created_at
`

type UpdatePaymentTransactionStatusParams struct {
	ID     pgtype.UUID
	Status string
}

type UpdatePaymentTransactionStatusRow struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	InvoiceID             pgtype.UUID
	Amount                pgtype.Numeric
	Provider              string
	ExternalTransactionID pgtype.Text
	Status                string
	PaymentMethod         pgtype.Text
	Payload               []byte
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) UpdatePaymentTransactionStatus(ctx context.Context, arg UpdatePaymentTransactionStatusParams) (UpdatePaymentTransactionStatusRow, error) {
	row := q.db.QueryRow(ctx, updatePaymentTransactionStatus, arg.ID, arg.Status)
	var i UpdatePaymentTransactionStatusRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.Amount,
		&i.Provider,
		&i.ExternalTransactionID,
		&i.Status,
		&i.PaymentMethod,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const updateWebhookEventStatus = `-- name: UpdateWebhookEventStatus :one
UPDATE webhook_events
SET status = $2,
    error = COALESCE($3, error),
    processed_at = CASE WHEN $2 = 'PROCESSED' OR $2 = 'FAILED' THEN NOW() ELSE processed_at END
WHERE id = $1
RETURNING id, provider, event_type, external_id, payload, status, error, processed_at, created_at
`

type UpdateWebhookEventStatusParams struct {
	ID     pgtype.UUID
	Status string
	Error  pgtype.Text
}

func (q *Queries) UpdateWebhookEventStatus(ctx context.Context, arg UpdateWebhookEventStatusParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, updateWebhookEventStatus, arg.ID, arg.Status, arg.Error)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventType,
		&i.ExternalID,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}
