// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation_jobs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGenerationJobsByOrganization = `-- name: CountGenerationJobsByOrganization :one
SELECT COUNT(*) FROM generation_jobs
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2)
`

type CountGenerationJobsByOrganizationParams struct {
	OrganizationID pgtype.UUID
	Status         pgtype.Text
}

func (q *Queries) CountGenerationJobsByOrganization(ctx context.Context, arg CountGenerationJobsByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGenerationJobsByOrganization, arg.OrganizationID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listGenerationJobsByOrganizationPaginated = `-- name: ListGenerationJobsByOrganizationPaginated :many
SELECT id, organization_id, user_id, type, status, input, result, error, credits_cost, started_at, finished_at, created_at, mind_map_id
FROM generation_jobs
WHERE organization_id = $1
  AND ($4::text IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListGenerationJobsByOrganizationPaginatedParams struct {
	OrganizationID pgtype.UUID
	Limit          int32
	Offset         int32
	Status         pgtype.Text
}

func (q *Queries) ListGenerationJobsByOrganizationPaginated(ctx context.Context, arg ListGenerationJobsByOrganizationPaginatedParams) ([]GenerationJob, error) {
	rows, err := q.db.Query(ctx, listGenerationJobsByOrganizationPaginated,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationJob
	for rows.Next() {
		var i GenerationJob
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Input,
			&i.Result,
			&i.Error,
			&i.CreditsCost,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.MindMapID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
