// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mindmaps.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMindMapsByOrganization = `-- name: CountMindMapsByOrganization :one
SELECT COUNT(*) FROM mind_maps WHERE organization_id = $1
`

func (q *Queries) CountMindMapsByOrganization(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMindMapsByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGenerationJob = `-- name: CreateGenerationJob :one
INSERT INTO generation_jobs (
    organization_id, user_id, type, status, input, credits_cost, started_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, user_id, type, status, input, result, error, credits_cost, started_at, finished_at, created_at, mind_map_id
`

type CreateGenerationJobParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Type           string
	Status         string
	Input          []byte
	CreditsCost    int32
	StartedAt      pgtype.Timestamptz
}

func (q *Queries) CreateGenerationJob(ctx context.Context, arg CreateGenerationJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, createGenerationJob,
		arg.OrganizationID,
		arg.UserID,
		arg.Type,
		arg.Status,
		arg.Input,
		arg.CreditsCost,
		arg.StartedAt,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Input,
		&i.Result,
		&i.Error,
		&i.CreditsCost,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.MindMapID,
	)
	return i, err
}

const createMindMap = `-- name: CreateMindMap :one
INSERT INTO mind_maps (
    organization_id, user_id, title, source_type, source_upload_id, status, json_data, is_public
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, user_id, title, source_type, source_upload_id, status, json_data, is_public, created_at, updated_at
`

type CreateMindMapParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Title          string
	SourceType     string
	SourceUploadID pgtype.UUID
	Status         string
	JsonData       json.RawMessage
	IsPublic       bool
}

func (q *Queries) CreateMindMap(ctx context.Context, arg CreateMindMapParams) (MindMap, error) {
	row := q.db.QueryRow(ctx, createMindMap,
		arg.OrganizationID,
		arg.UserID,
		arg.Title,
		arg.SourceType,
		arg.SourceUploadID,
		arg.Status,
		arg.JsonData,
		arg.IsPublic,
	)
	var i MindMap
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Title,
		&i.SourceType,
		&i.SourceUploadID,
		&i.Status,
		&i.JsonData,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMindMap = `-- name: DeleteMindMap :exec
DELETE FROM mind_maps WHERE id = $1
`

func (q *Queries) DeleteMindMap(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMindMap, id)
	return err
}

const getGenerationJob = `-- name: GetGenerationJob :one
SELECT id, organization_id, user_id, type, status, input, result, error, credits_cost, started_at, finished_at, created_at, mind_map_id
FROM generation_jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGenerationJob(ctx context.Context, id pgtype.UUID) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJob, id)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Input,
		&i.Result,
		&i.Error,
		&i.CreditsCost,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.MindMapID,
	)
	return i, err
}

const getMindMap = `-- name: GetMindMap :one
SELECT id, organization_id, user_id, title, source_type, source_upload_id, status, json_data, is_public, created_at, updated_at
FROM mind_maps
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMindMap(ctx context.Context, id pgtype.UUID) (MindMap, error) {
	row := q.db.QueryRow(ctx, getMindMap, id)
	var i MindMap
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Title,
		&i.SourceType,
		&i.SourceUploadID,
		&i.Status,
		&i.JsonData,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGenerationJobsByOrganization = `-- name: ListGenerationJobsByOrganization :many
SELECT id, organization_id, user_id, type, status, input, result, error, credits_cost, started_at, finished_at, created_at, mind_map_id
FROM generation_jobs
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListGenerationJobsByOrganizationParams struct {
	OrganizationID pgtype.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListGenerationJobsByOrganization(ctx context.Context, arg ListGenerationJobsByOrganizationParams) ([]GenerationJob, error) {
	rows, err := q.db.Query(ctx, listGenerationJobsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationJob
	for rows.Next() {
		var i GenerationJob
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Input,
			&i.Result,
			&i.Error,
			&i.CreditsCost,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.MindMapID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMindMapsByOrganization = `-- name: ListMindMapsByOrganization :many
SELECT id, organization_id, user_id, title, source_type, source_upload_id, status, json_data, is_public, created_at, updated_at
FROM mind_maps
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMindMapsByOrganizationParams struct {
	OrganizationID pgtype.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListMindMapsByOrganization(ctx context.Context, arg ListMindMapsByOrganizationParams) ([]MindMap, error) {
	rows, err := q.db.Query(ctx, listMindMapsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindMap
	for rows.Next() {
		var i MindMap
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Title,
			&i.SourceType,
			&i.SourceUploadID,
			&i.Status,
			&i.JsonData,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMindMapsByOrganization = `-- name: ListRecentMindMapsByOrganization :many
SELECT id, organization_id, user_id, title, source_type, status, created_at, updated_at
FROM mind_maps
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentMindMapsByOrganizationParams struct {
	OrganizationID pgtype.UUID
	Limit          int32
}

type ListRecentMindMapsByOrganizationRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Title          string
	SourceType     string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListRecentMindMapsByOrganization(ctx context.Context, arg ListRecentMindMapsByOrganizationParams) ([]ListRecentMindMapsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listRecentMindMapsByOrganization, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentMindMapsByOrganizationRow
	for rows.Next() {
		var i ListRecentMindMapsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Title,
			&i.SourceType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenerationJobError = `-- name: UpdateGenerationJobError :one
UPDATE generation_jobs
SET status = 'FAILED',
    error = $2,
    finished_at = NOW()
WHERE id = $1
RETURNING id, organization_id, user_id, type, status, input, result, error, credits_cost, started_at, finished_at, created_at, mind_map_id
`

type UpdateGenerationJobErrorParams struct {
	ID    pgtype.UUID
	Error pgtype.Text
}

func (q *Queries) UpdateGenerationJobError(ctx context.Context, arg UpdateGenerationJobErrorParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, updateGenerationJobError, arg.ID, arg.Error)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Input,
		&i.Result,
		&i.Error,
		&i.CreditsCost,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.MindMapID,
	)
	return i, err
}

const updateGenerationJobResult = `-- name: UpdateGenerationJobResult :one
UPDATE generation_jobs
SET status = 'COMPLETED',
    result = $2,
    mind_map_id = $3,
    finished_at = NOW()
WHERE id = $1
RETURNING id, organization_id, user_id, type, status, input, result, error, credits_cost, started_at, finished_at, created_at, mind_map_id
`

type UpdateGenerationJobResultParams struct {
	ID        pgtype.UUID
	Result    []byte
	MindMapID pgtype.UUID
}

func (q *Queries) UpdateGenerationJobResult(ctx context.Context, arg UpdateGenerationJobResultParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, updateGenerationJobResult, arg.ID, arg.Result, arg.MindMapID)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Input,
		&i.Result,
		&i.Error,
		&i.CreditsCost,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.MindMapID,
	)
	return i, err
}

const updateGenerationJobStatus = `-- name: UpdateGenerationJobStatus :one
UPDATE generation_jobs
SET status = $2,
    started_at = CASE WHEN $2 = 'PROCESSING' THEN NOW() ELSE started_at END,
    finished_at = CASE WHEN $2 = 'COMPLETED' OR $2 = 'FAILED' THEN NOW() ELSE finished_at END
WHERE id = $1
RETURNING id, organization_id, user_id, type, status, input, result, error, credits_cost, started_at, finished_at, created_at, mind_map_id
`

type UpdateGenerationJobStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateGenerationJobStatus(ctx context.Context, arg UpdateGenerationJobStatusParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, updateGenerationJobStatus, arg.ID, arg.Status)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Input,
		&i.Result,
		&i.Error,
		&i.CreditsCost,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.MindMapID,
	)
	return i, err
}

const updateMindMapData = `-- name: UpdateMindMapData :one
UPDATE mind_maps
SET title = COALESCE($2, title),
    json_data = COALESCE($3, json_data),
    is_public = COALESCE($4, is_public),
    status = COALESCE($5, status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, user_id, title, source_type, source_upload_id, status, json_data, is_public, created_at, updated_at
`

type UpdateMindMapDataParams struct {
	ID       pgtype.UUID
	Title    string
	JsonData json.RawMessage
	IsPublic bool
	Status   string
}

func (q *Queries) UpdateMindMapData(ctx context.Context, arg UpdateMindMapDataParams) (MindMap, error) {
	row := q.db.QueryRow(ctx, updateMindMapData,
		arg.ID,
		arg.Title,
		arg.JsonData,
		arg.IsPublic,
		arg.Status,
	)
	var i MindMap
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Title,
		&i.SourceType,
		&i.SourceUploadID,
		&i.Status,
		&i.JsonData,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
