// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AiActionPrice struct {
	ID          pgtype.UUID
	ActionKey   string
	Name        string
	Description pgtype.Text
	CreditsCost int32
	IsActive    bool
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AiCreditBalance struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Balance        int32
	UpdatedAt      pgtype.Timestamptz
}

type AiCreditTransaction struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Amount         int32
	Type           string
	Description    string
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
}

type AiProvider struct {
	ID                  pgtype.UUID
	Name                string
	Slug                string
	ApiKeySecure        string
	BaseUrl             pgtype.Text
	DefaultModel        string
	TextModel           string
	VisionModel         string
	AudioModel          string
	EmbeddingModel      string
	EmbeddingDimensions int32
	IsActive            bool
	Priority            int32
	IsDefault           bool
	LimitPerMinute      int32
	LimitPerDay         int32
	CostPerCredit       pgtype.Numeric
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type AuditLog struct {
	ID             pgtype.UUID
	ActorUserID    pgtype.UUID
	OrganizationID pgtype.UUID
	Action         string
	EntityType     string
	EntityID       pgtype.UUID
	Metadata       []byte
	Ip             pgtype.Text
	UserAgent      pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type DocumentChunk struct {
	ID               pgtype.UUID
	DocumentSourceID pgtype.UUID
	OrganizationID   pgtype.UUID
	Content          string
	ChunkIndex       int32
	TokenCount       int32
	Embedding        pgvector.Vector
	Metadata         []byte
	CreatedAt        pgtype.Timestamptz
}

type DocumentSource struct {
	ID             pgtype.UUID
	UploadID       pgtype.UUID
	OrganizationID pgtype.UUID
	Title          string
	Status         string
	WordCount      int32
	ChunkCount     int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Flashcard struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	MindMapID      pgtype.UUID
	Question       string
	Answer         string
	Difficulty     string
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type FlashcardReview struct {
	ID           pgtype.UUID
	FlashcardID  pgtype.UUID
	UserID       pgtype.UUID
	Result       string
	NextReviewAt pgtype.Timestamptz
	ReviewedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type GenerationJob struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Type           string
	Status         string
	Input          []byte
	Result         []byte
	Error          pgtype.Text
	CreditsCost    int32
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type Integration struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Type           string
	Config         string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Invoice struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	SubscriptionID    pgtype.UUID
	Amount            pgtype.Numeric
	Currency          string
	Status            string
	ExternalInvoiceID pgtype.Text
	PdfUrl            pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type MindMap struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Title          string
	SourceType     string
	SourceUploadID pgtype.UUID
	Status         string
	JsonData       json.RawMessage
	IsPublic       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OrganizationUser struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type PaymentProvider struct {
	ID                  pgtype.UUID
	Name                string
	Slug                string
	ApiKeySecure        pgtype.Text
	WebhookSecretSecure pgtype.Text
	IsActive            bool
	CreatedAt           pgtype.Timestamptz
}

type PaymentTransaction struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	InvoiceID             pgtype.UUID
	Amount                pgtype.Numeric
	Provider              string
	ExternalTransactionID pgtype.Text
	Status                string
	Payload               []byte
	CreatedAt             pgtype.Timestamptz
}

type Plan struct {
	ID                   pgtype.UUID
	Name                 string
	Description          pgtype.Text
	PriceMonthly         pgtype.Numeric
	PriceYearly          pgtype.Numeric
	Currency             string
	CreditsMonthly       int32
	MaxMaps              int32
	MaxFiles             int32
	MaxUsers             int32
	MaxStorageBytes      int64
	Features             json.RawMessage
	IsPublic             bool
	IsActive             bool
	TargetOrganizationID pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Subscription struct {
	ID                     pgtype.UUID
	OrganizationID         pgtype.UUID
	PlanID                 pgtype.UUID
	Status                 string
	PaymentProvider        string
	ExternalSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	TrialStart             pgtype.Timestamptz
	TrialEnd               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type SystemSetting struct {
	Key         string
	Value       json.RawMessage
	Description pgtype.Text
	IsPublic    bool
	UpdatedAt   pgtype.Timestamptz
}

type Upload struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	UserID          pgtype.UUID
	Filename        string
	OriginalName    string
	MimeType        string
	Size            int64
	StorageProvider string
	StorageKey      string
	Status          string
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	Name            string
	GlobalRole      string
	Status          string
	LastLoginAt     pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type WebhookEvent struct {
	ID          pgtype.UUID
	Provider    string
	EventType   string
	ExternalID  string
	Payload     json.RawMessage
	Status      string
	Error       pgtype.Text
	ProcessedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
