// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizationUsers = `-- name: CountOrganizationUsers :one
SELECT COUNT(*) FROM organization_users WHERE organization_id = $1
`

func (q *Queries) CountOrganizationUsers(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationUsers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, status)
VALUES ($1, $2, $3)
RETURNING id, name, slug, status, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name   string
	Slug   string
	Status string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug, arg.Status)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationUser = `-- name: CreateOrganizationUser :one
INSERT INTO organization_users (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, role, created_at, updated_at
`

type CreateOrganizationUserParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
}

func (q *Queries) CreateOrganizationUser(ctx context.Context, arg CreateOrganizationUserParams) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, createOrganizationUser, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationUser
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, status, created_at, updated_at
FROM organizations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, status, created_at, updated_at
FROM organizations
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationSummary = `-- name: GetOrganizationSummary :one
SELECT o.id, o.name, o.slug, o.status, o.created_at,
       (SELECT COUNT(*) FROM organization_users ou WHERE ou.organization_id = o.id) as users_count,
       (SELECT COUNT(*) FROM mind_maps m WHERE m.organization_id = o.id) as maps_count,
       (SELECT COUNT(*) FROM uploads up WHERE up.organization_id = o.id AND up.status != 'FAILED') as uploads_count,
       (SELECT COALESCE(SUM(up.size), 0)::bigint FROM uploads up WHERE up.organization_id = o.id AND up.status != 'FAILED') as total_storage_bytes,
       (SELECT COALESCE(cb.balance, 0)::int FROM ai_credit_balances cb WHERE cb.organization_id = o.id LIMIT 1) as credits_balance
FROM organizations o
WHERE o.id = $1 LIMIT 1
`

type GetOrganizationSummaryRow struct {
	ID                pgtype.UUID
	Name              string
	Slug              string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UsersCount        int64
	MapsCount         int64
	UploadsCount      int64
	TotalStorageBytes int64
	CreditsBalance    int32
}

func (q *Queries) GetOrganizationSummary(ctx context.Context, id pgtype.UUID) (GetOrganizationSummaryRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationSummary, id)
	var i GetOrganizationSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UsersCount,
		&i.MapsCount,
		&i.UploadsCount,
		&i.TotalStorageBytes,
		&i.CreditsBalance,
	)
	return i, err
}

const getOrganizationUser = `-- name: GetOrganizationUser :one
SELECT id, organization_id, user_id, role, created_at, updated_at
FROM organization_users
WHERE organization_id = $1 AND user_id = $2 LIMIT 1
`

type GetOrganizationUserParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) GetOrganizationUser(ctx context.Context, arg GetOrganizationUserParams) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, getOrganizationUser, arg.OrganizationID, arg.UserID)
	var i OrganizationUser
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT ou.organization_id, o.name AS organization_name, o.slug AS organization_slug, o.status AS organization_status, ou.role
FROM organization_users ou
JOIN organizations o ON o.id = ou.organization_id
WHERE ou.user_id = $1
`

type GetUserOrganizationsRow struct {
	OrganizationID     pgtype.UUID
	OrganizationName   string
	OrganizationSlug   string
	OrganizationStatus string
	Role               string
}

func (q *Queries) GetUserOrganizations(ctx context.Context, userID pgtype.UUID) ([]GetUserOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, getUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrganizationsRow
	for rows.Next() {
		var i GetUserOrganizationsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.OrganizationStatus,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationUsers = `-- name: ListOrganizationUsers :many
SELECT ou.id, ou.organization_id, ou.user_id, ou.role, ou.created_at,
       u.email, u.name as user_name
FROM organization_users ou
JOIN users u ON ou.user_id = u.id
WHERE ou.organization_id = $1
`

type ListOrganizationUsersRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
	CreatedAt      pgtype.Timestamptz
	Email          string
	UserName       string
}

func (q *Queries) ListOrganizationUsers(ctx context.Context, organizationID pgtype.UUID) ([]ListOrganizationUsersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationUsers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationUsersRow
	for rows.Next() {
		var i ListOrganizationUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, status, created_at
FROM organizations
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32
	Offset int32
}

type ListOrganizationsRow struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsRow
	for rows.Next() {
		var i ListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrganizationUser = `-- name: RemoveOrganizationUser :exec
DELETE FROM organization_users
WHERE organization_id = $1 AND user_id = $2
`

type RemoveOrganizationUserParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) RemoveOrganizationUser(ctx context.Context, arg RemoveOrganizationUserParams) error {
	_, err := q.db.Exec(ctx, removeOrganizationUser, arg.OrganizationID, arg.UserID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    status = COALESCE($4, status)
WHERE id = $1
RETURNING id, name, slug, status, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID     pgtype.UUID
	Name   string
	Slug   string
	Status string
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Status,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationUserRole = `-- name: UpdateOrganizationUserRole :one
UPDATE organization_users
SET role = $3
WHERE organization_id = $1 AND user_id = $2
RETURNING id, organization_id, user_id, role, created_at, updated_at
`

type UpdateOrganizationUserRoleParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Role           string
}

func (q *Queries) UpdateOrganizationUserRole(ctx context.Context, arg UpdateOrganizationUserRoleParams) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, updateOrganizationUserRole, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationUser
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
