// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlans = `-- name: CountPlans :one
SELECT COUNT(*) FROM plans
`

func (q *Queries) CountPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubscriptions = `-- name: CountSubscriptions :one
SELECT COUNT(*) FROM subscriptions
`

func (q *Queries) CountSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    name, description, price_monthly, price_yearly, currency,
    credits_monthly, max_maps, max_files, max_users, max_storage_bytes,
    features, is_public, is_active, target_organization_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, name, description, price_monthly, price_yearly, currency, credits_monthly, max_maps, max_files, max_users, max_storage_bytes, features, is_public, is_active, target_organization_id, created_at, updated_at
`

type CreatePlanParams struct {
	Name                 string
	Description          pgtype.Text
	PriceMonthly         pgtype.Numeric
	PriceYearly          pgtype.Numeric
	Currency             string
	CreditsMonthly       int32
	MaxMaps              int32
	MaxFiles             int32
	MaxUsers             int32
	MaxStorageBytes      int64
	Features             json.RawMessage
	IsPublic             bool
	IsActive             bool
	TargetOrganizationID pgtype.UUID
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Name,
		arg.Description,
		arg.PriceMonthly,
		arg.PriceYearly,
		arg.Currency,
		arg.CreditsMonthly,
		arg.MaxMaps,
		arg.MaxFiles,
		arg.MaxUsers,
		arg.MaxStorageBytes,
		arg.Features,
		arg.IsPublic,
		arg.IsActive,
		arg.TargetOrganizationID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.Currency,
		&i.CreditsMonthly,
		&i.MaxMaps,
		&i.MaxFiles,
		&i.MaxUsers,
		&i.MaxStorageBytes,
		&i.Features,
		&i.IsPublic,
		&i.IsActive,
		&i.TargetOrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    organization_id, plan_id, status, payment_provider,
    external_subscription_id, current_period_start, current_period_end,
    trial_start, trial_end
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, plan_id, status, payment_provider, external_subscription_id, current_period_start, current_period_end, trial_start, trial_end, created_at, updated_at
`

type CreateSubscriptionParams struct {
	OrganizationID         pgtype.UUID
	PlanID                 pgtype.UUID
	Status                 string
	PaymentProvider        string
	ExternalSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	TrialStart             pgtype.Timestamptz
	TrialEnd               pgtype.Timestamptz
}

type CreateSubscriptionRow struct {
	ID                     pgtype.UUID
	OrganizationID         pgtype.UUID
	PlanID                 pgtype.UUID
	Status                 string
	PaymentProvider        string
	ExternalSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	TrialStart             pgtype.Timestamptz
	TrialEnd               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.OrganizationID,
		arg.PlanID,
		arg.Status,
		arg.PaymentProvider,
		arg.ExternalSubscriptionID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.TrialStart,
		arg.TrialEnd,
	)
	var i CreateSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.PaymentProvider,
		&i.ExternalSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialStart,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, description, price_monthly, price_yearly, currency, credits_monthly, max_maps, max_files, max_users, max_storage_bytes, features, is_public, is_active, target_organization_id, created_at, updated_at
FROM plans
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.Currency,
		&i.CreditsMonthly,
		&i.MaxMaps,
		&i.MaxFiles,
		&i.MaxUsers,
		&i.MaxStorageBytes,
		&i.Features,
		&i.IsPublic,
		&i.IsActive,
		&i.TargetOrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByOrg = `-- name: GetSubscriptionByOrg :one
SELECT id, organization_id, plan_id, status, payment_provider, external_subscription_id, current_period_start, current_period_end, trial_start, trial_end, created_at, updated_at
FROM subscriptions
WHERE organization_id = $1 LIMIT 1
`

type GetSubscriptionByOrgRow struct {
	ID                     pgtype.UUID
	OrganizationID         pgtype.UUID
	PlanID                 pgtype.UUID
	Status                 string
	PaymentProvider        string
	ExternalSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	TrialStart             pgtype.Timestamptz
	TrialEnd               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) GetSubscriptionByOrg(ctx context.Context, organizationID pgtype.UUID) (GetSubscriptionByOrgRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByOrg, organizationID)
	var i GetSubscriptionByOrgRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.PaymentProvider,
		&i.ExternalSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialStart,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, price_monthly, price_yearly, currency, is_public, is_active, target_organization_id, created_at
FROM plans
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPlansParams struct {
	Limit  int32
	Offset int32
}

type ListPlansRow struct {
	ID                   pgtype.UUID
	Name                 string
	PriceMonthly         pgtype.Numeric
	PriceYearly          pgtype.Numeric
	Currency             string
	IsPublic             bool
	IsActive             bool
	TargetOrganizationID pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]ListPlansRow, error) {
	rows, err := q.db.Query(ctx, listPlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansRow
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceMonthly,
			&i.PriceYearly,
			&i.Currency,
			&i.IsPublic,
			&i.IsActive,
			&i.TargetOrganizationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicPlans = `-- name: ListPublicPlans :many
SELECT id, name, description, price_monthly, price_yearly, currency, credits_monthly, max_maps, max_files, max_users, max_storage_bytes, features, is_public, is_active, created_at
FROM plans
WHERE is_public = TRUE AND is_active = TRUE
ORDER BY price_monthly ASC
`

type ListPublicPlansRow struct {
	ID              pgtype.UUID
	Name            string
	Description     pgtype.Text
	PriceMonthly    pgtype.Numeric
	PriceYearly     pgtype.Numeric
	Currency        string
	CreditsMonthly  int32
	MaxMaps         int32
	MaxFiles        int32
	MaxUsers        int32
	MaxStorageBytes int64
	Features        json.RawMessage
	IsPublic        bool
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListPublicPlans(ctx context.Context) ([]ListPublicPlansRow, error) {
	rows, err := q.db.Query(ctx, listPublicPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicPlansRow
	for rows.Next() {
		var i ListPublicPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceMonthly,
			&i.PriceYearly,
			&i.Currency,
			&i.CreditsMonthly,
			&i.MaxMaps,
			&i.MaxFiles,
			&i.MaxUsers,
			&i.MaxStorageBytes,
			&i.Features,
			&i.IsPublic,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT s.id, s.organization_id, s.plan_id, s.status, s.payment_provider, s.external_subscription_id, s.current_period_start, s.current_period_end, s.created_at,
       o.name as organization_name, p.name as plan_name
FROM subscriptions s
JOIN organizations o ON s.organization_id = o.id
JOIN plans p ON s.plan_id = p.id
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubscriptionsParams struct {
	Limit  int32
	Offset int32
}

type ListSubscriptionsRow struct {
	ID                     pgtype.UUID
	OrganizationID         pgtype.UUID
	PlanID                 pgtype.UUID
	Status                 string
	PaymentProvider        string
	ExternalSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	OrganizationName       string
	PlanName               string
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]ListSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsRow
	for rows.Next() {
		var i ListSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PlanID,
			&i.Status,
			&i.PaymentProvider,
			&i.ExternalSubscriptionID,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CreatedAt,
			&i.OrganizationName,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    price_monthly = COALESCE($4, price_monthly),
    price_yearly = COALESCE($5, price_yearly),
    currency = COALESCE($6, currency),
    credits_monthly = COALESCE($7, credits_monthly),
    max_maps = COALESCE($8, max_maps),
    max_files = COALESCE($9, max_files),
    max_users = COALESCE($10, max_users),
    max_storage_bytes = COALESCE($11, max_storage_bytes),
    features = COALESCE($12, features),
    is_public = COALESCE($13, is_public),
    is_active = COALESCE($14, is_active),
    target_organization_id = COALESCE($15, target_organization_id)
WHERE id = $1
RETURNING id, name, description, price_monthly, price_yearly, currency, credits_monthly, max_maps, max_files, max_users, max_storage_bytes, features, is_public, is_active, target_organization_id, created_at, updated_at
`

type UpdatePlanParams struct {
	ID                   pgtype.UUID
	Name                 string
	Description          pgtype.Text
	PriceMonthly         pgtype.Numeric
	PriceYearly          pgtype.Numeric
	Currency             string
	CreditsMonthly       int32
	MaxMaps              int32
	MaxFiles             int32
	MaxUsers             int32
	MaxStorageBytes      int64
	Features             json.RawMessage
	IsPublic             bool
	IsActive             bool
	TargetOrganizationID pgtype.UUID
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceMonthly,
		arg.PriceYearly,
		arg.Currency,
		arg.CreditsMonthly,
		arg.MaxMaps,
		arg.MaxFiles,
		arg.MaxUsers,
		arg.MaxStorageBytes,
		arg.Features,
		arg.IsPublic,
		arg.IsActive,
		arg.TargetOrganizationID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceMonthly,
		&i.PriceYearly,
		&i.Currency,
		&i.CreditsMonthly,
		&i.MaxMaps,
		&i.MaxFiles,
		&i.MaxUsers,
		&i.MaxStorageBytes,
		&i.Features,
		&i.IsPublic,
		&i.IsActive,
		&i.TargetOrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET plan_id = COALESCE($2, plan_id),
    status = COALESCE($3, status),
    payment_provider = COALESCE($4, payment_provider),
    external_subscription_id = COALESCE($5, external_subscription_id),
    current_period_start = COALESCE($6, current_period_start),
    current_period_end = COALESCE($7, current_period_end),
    trial_start = COALESCE($8, trial_start),
    trial_end = COALESCE($9, trial_end)
WHERE id = $1
RETURNING id, organization_id, plan_id, status, payment_provider, external_subscription_id, current_period_start, current_period_end, trial_start, trial_end, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID                     pgtype.UUID
	PlanID                 pgtype.UUID
	Status                 string
	PaymentProvider        string
	ExternalSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	TrialStart             pgtype.Timestamptz
	TrialEnd               pgtype.Timestamptz
}

type UpdateSubscriptionRow struct {
	ID                     pgtype.UUID
	OrganizationID         pgtype.UUID
	PlanID                 pgtype.UUID
	Status                 string
	PaymentProvider        string
	ExternalSubscriptionID pgtype.Text
	CurrentPeriodStart     pgtype.Timestamptz
	CurrentPeriodEnd       pgtype.Timestamptz
	TrialStart             pgtype.Timestamptz
	TrialEnd               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (UpdateSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.PlanID,
		arg.Status,
		arg.PaymentProvider,
		arg.ExternalSubscriptionID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.TrialStart,
		arg.TrialEnd,
	)
	var i UpdateSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.PaymentProvider,
		&i.ExternalSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialStart,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
