// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rag.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createDocumentChunk = `-- name: CreateDocumentChunk :one
INSERT INTO document_chunks (
    document_source_id, organization_id, content, chunk_index, token_count, embedding, metadata
)
VALUES ($1, $2, $3, $4, $5, $7::vector, $6)
RETURNING id, document_source_id, organization_id, content, chunk_index, token_count, created_at
`

type CreateDocumentChunkParams struct {
	DocumentSourceID pgtype.UUID
	OrganizationID   pgtype.UUID
	Content          string
	ChunkIndex       int32
	TokenCount       int32
	Metadata         []byte
	Embedding        pgvector.Vector
}

type CreateDocumentChunkRow struct {
	ID               pgtype.UUID
	DocumentSourceID pgtype.UUID
	OrganizationID   pgtype.UUID
	Content          string
	ChunkIndex       int32
	TokenCount       int32
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateDocumentChunk(ctx context.Context, arg CreateDocumentChunkParams) (CreateDocumentChunkRow, error) {
	row := q.db.QueryRow(ctx, createDocumentChunk,
		arg.DocumentSourceID,
		arg.OrganizationID,
		arg.Content,
		arg.ChunkIndex,
		arg.TokenCount,
		arg.Metadata,
		arg.Embedding,
	)
	var i CreateDocumentChunkRow
	err := row.Scan(
		&i.ID,
		&i.DocumentSourceID,
		&i.OrganizationID,
		&i.Content,
		&i.ChunkIndex,
		&i.TokenCount,
		&i.CreatedAt,
	)
	return i, err
}

const createDocumentSource = `-- name: CreateDocumentSource :one
INSERT INTO document_sources (
    upload_id, organization_id, title, status, word_count, chunk_count
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, upload_id, organization_id, title, status, word_count, chunk_count, created_at, updated_at
`

type CreateDocumentSourceParams struct {
	UploadID       pgtype.UUID
	OrganizationID pgtype.UUID
	Title          string
	Status         string
	WordCount      int32
	ChunkCount     int32
}

func (q *Queries) CreateDocumentSource(ctx context.Context, arg CreateDocumentSourceParams) (DocumentSource, error) {
	row := q.db.QueryRow(ctx, createDocumentSource,
		arg.UploadID,
		arg.OrganizationID,
		arg.Title,
		arg.Status,
		arg.WordCount,
		arg.ChunkCount,
	)
	var i DocumentSource
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.OrganizationID,
		&i.Title,
		&i.Status,
		&i.WordCount,
		&i.ChunkCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentChunksBySource = `-- name: GetDocumentChunksBySource :many
SELECT id, content, chunk_index, token_count
FROM document_chunks
WHERE document_source_id = $1
ORDER BY chunk_index ASC
LIMIT $2
`

type GetDocumentChunksBySourceParams struct {
	DocumentSourceID pgtype.UUID
	Limit            int32
}

type GetDocumentChunksBySourceRow struct {
	ID         pgtype.UUID
	Content    string
	ChunkIndex int32
	TokenCount int32
}

func (q *Queries) GetDocumentChunksBySource(ctx context.Context, arg GetDocumentChunksBySourceParams) ([]GetDocumentChunksBySourceRow, error) {
	rows, err := q.db.Query(ctx, getDocumentChunksBySource, arg.DocumentSourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentChunksBySourceRow
	for rows.Next() {
		var i GetDocumentChunksBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.ChunkIndex,
			&i.TokenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentSourceByUpload = `-- name: GetDocumentSourceByUpload :one
SELECT id, upload_id, organization_id, title, status, word_count, chunk_count, created_at, updated_at
FROM document_sources
WHERE upload_id = $1 LIMIT 1
`

func (q *Queries) GetDocumentSourceByUpload(ctx context.Context, uploadID pgtype.UUID) (DocumentSource, error) {
	row := q.db.QueryRow(ctx, getDocumentSourceByUpload, uploadID)
	var i DocumentSource
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.OrganizationID,
		&i.Title,
		&i.Status,
		&i.WordCount,
		&i.ChunkCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchSimilarChunks = `-- name: SearchSimilarChunks :many
SELECT c.id, c.content, c.chunk_index, c.document_source_id,
       (1 - (c.embedding <=> $4::vector))::float8 AS similarity
FROM document_chunks c
JOIN document_sources s ON s.id = c.document_source_id
WHERE c.organization_id = $1
  AND s.upload_id = $2
ORDER BY c.embedding <=> $4::vector
LIMIT $3
`

type SearchSimilarChunksParams struct {
	OrganizationID pgtype.UUID
	UploadID       pgtype.UUID
	Limit          int32
	QueryEmbedding pgvector.Vector
}

type SearchSimilarChunksRow struct {
	ID               pgtype.UUID
	Content          string
	ChunkIndex       int32
	DocumentSourceID pgtype.UUID
	Similarity       float64
}

func (q *Queries) SearchSimilarChunks(ctx context.Context, arg SearchSimilarChunksParams) ([]SearchSimilarChunksRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarChunks,
		arg.OrganizationID,
		arg.UploadID,
		arg.Limit,
		arg.QueryEmbedding,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSimilarChunksRow
	for rows.Next() {
		var i SearchSimilarChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.ChunkIndex,
			&i.DocumentSourceID,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentSourceStatus = `-- name: UpdateDocumentSourceStatus :one
UPDATE document_sources
SET status = $2, chunk_count = $3, word_count = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, status, chunk_count, word_count, updated_at
`

type UpdateDocumentSourceStatusParams struct {
	ID         pgtype.UUID
	Status     string
	ChunkCount int32
	WordCount  int32
}

type UpdateDocumentSourceStatusRow struct {
	ID         pgtype.UUID
	Status     string
	ChunkCount int32
	WordCount  int32
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateDocumentSourceStatus(ctx context.Context, arg UpdateDocumentSourceStatusParams) (UpdateDocumentSourceStatusRow, error) {
	row := q.db.QueryRow(ctx, updateDocumentSourceStatus,
		arg.ID,
		arg.Status,
		arg.ChunkCount,
		arg.WordCount,
	)
	var i UpdateDocumentSourceStatusRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ChunkCount,
		&i.WordCount,
		&i.UpdatedAt,
	)
	return i, err
}
