// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAiActionPrice = `-- name: CreateAiActionPrice :one
INSERT INTO ai_action_prices (action_key, name, description, credits_cost, is_active, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, action_key, name, description, credits_cost, is_active, metadata, created_at, updated_at
`

type CreateAiActionPriceParams struct {
	ActionKey   string
	Name        string
	Description pgtype.Text
	CreditsCost int32
	IsActive    bool
	Metadata    []byte
}

func (q *Queries) CreateAiActionPrice(ctx context.Context, arg CreateAiActionPriceParams) (AiActionPrice, error) {
	row := q.db.QueryRow(ctx, createAiActionPrice,
		arg.ActionKey,
		arg.Name,
		arg.Description,
		arg.CreditsCost,
		arg.IsActive,
		arg.Metadata,
	)
	var i AiActionPrice
	err := row.Scan(
		&i.ID,
		&i.ActionKey,
		&i.Name,
		&i.Description,
		&i.CreditsCost,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAiProvider = `-- name: CreateAiProvider :one
INSERT INTO ai_providers (
    name, slug, api_key_secure, base_url, default_model, text_model,
    vision_model, audio_model, embedding_model, embedding_dimensions,
    is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, name, slug, api_key_secure, base_url, default_model, text_model, vision_model, audio_model, embedding_model, embedding_dimensions, is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit, created_at, updated_at
`

type CreateAiProviderParams struct {
	Name                string
	Slug                string
	ApiKeySecure        string
	BaseUrl             pgtype.Text
	DefaultModel        string
	TextModel           string
	VisionModel         string
	AudioModel          string
	EmbeddingModel      string
	EmbeddingDimensions int32
	IsActive            bool
	Priority            int32
	IsDefault           bool
	LimitPerMinute      int32
	LimitPerDay         int32
	CostPerCredit       pgtype.Numeric
}

func (q *Queries) CreateAiProvider(ctx context.Context, arg CreateAiProviderParams) (AiProvider, error) {
	row := q.db.QueryRow(ctx, createAiProvider,
		arg.Name,
		arg.Slug,
		arg.ApiKeySecure,
		arg.BaseUrl,
		arg.DefaultModel,
		arg.TextModel,
		arg.VisionModel,
		arg.AudioModel,
		arg.EmbeddingModel,
		arg.EmbeddingDimensions,
		arg.IsActive,
		arg.Priority,
		arg.IsDefault,
		arg.LimitPerMinute,
		arg.LimitPerDay,
		arg.CostPerCredit,
	)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.BaseUrl,
		&i.DefaultModel,
		&i.TextModel,
		&i.VisionModel,
		&i.AudioModel,
		&i.EmbeddingModel,
		&i.EmbeddingDimensions,
		&i.IsActive,
		&i.Priority,
		&i.IsDefault,
		&i.LimitPerMinute,
		&i.LimitPerDay,
		&i.CostPerCredit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditTransaction = `-- name: CreateCreditTransaction :one
INSERT INTO ai_credit_transactions (organization_id, amount, type, description, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, amount, type, description, metadata, created_at
`

type CreateCreditTransactionParams struct {
	OrganizationID pgtype.UUID
	Amount         int32
	Type           string
	Description    string
	Metadata       []byte
}

func (q *Queries) CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (AiCreditTransaction, error) {
	row := q.db.QueryRow(ctx, createCreditTransaction,
		arg.OrganizationID,
		arg.Amount,
		arg.Type,
		arg.Description,
		arg.Metadata,
	)
	var i AiCreditTransaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAiActionPrice = `-- name: GetAiActionPrice :one
SELECT id, action_key, name, description, credits_cost, is_active, metadata, created_at, updated_at
FROM ai_action_prices
WHERE action_key = $1 LIMIT 1
`

func (q *Queries) GetAiActionPrice(ctx context.Context, actionKey string) (AiActionPrice, error) {
	row := q.db.QueryRow(ctx, getAiActionPrice, actionKey)
	var i AiActionPrice
	err := row.Scan(
		&i.ID,
		&i.ActionKey,
		&i.Name,
		&i.Description,
		&i.CreditsCost,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAiProviderBySlug = `-- name: GetAiProviderBySlug :one
SELECT id, name, slug, api_key_secure, base_url, default_model, text_model, vision_model, audio_model, embedding_model, embedding_dimensions, is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit, created_at, updated_at
FROM ai_providers
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetAiProviderBySlug(ctx context.Context, slug string) (AiProvider, error) {
	row := q.db.QueryRow(ctx, getAiProviderBySlug, slug)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.BaseUrl,
		&i.DefaultModel,
		&i.TextModel,
		&i.VisionModel,
		&i.AudioModel,
		&i.EmbeddingModel,
		&i.EmbeddingDimensions,
		&i.IsActive,
		&i.Priority,
		&i.IsDefault,
		&i.LimitPerMinute,
		&i.LimitPerDay,
		&i.CostPerCredit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditBalance = `-- name: GetCreditBalance :one
SELECT id, organization_id, balance, updated_at
FROM ai_credit_balances
WHERE organization_id = $1 LIMIT 1
`

func (q *Queries) GetCreditBalance(ctx context.Context, organizationID pgtype.UUID) (AiCreditBalance, error) {
	row := q.db.QueryRow(ctx, getCreditBalance, organizationID)
	var i AiCreditBalance
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Balance,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultAiProvider = `-- name: GetDefaultAiProvider :one
SELECT id, name, slug, api_key_secure, base_url, default_model, text_model, vision_model, audio_model, embedding_model, embedding_dimensions, is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit
FROM ai_providers
WHERE is_active = TRUE AND is_default = TRUE LIMIT 1
`

type GetDefaultAiProviderRow struct {
	ID                  pgtype.UUID
	Name                string
	Slug                string
	ApiKeySecure        string
	BaseUrl             pgtype.Text
	DefaultModel        string
	TextModel           string
	VisionModel         string
	AudioModel          string
	EmbeddingModel      string
	EmbeddingDimensions int32
	IsActive            bool
	Priority            int32
	IsDefault           bool
	LimitPerMinute      int32
	LimitPerDay         int32
	CostPerCredit       pgtype.Numeric
}

func (q *Queries) GetDefaultAiProvider(ctx context.Context) (GetDefaultAiProviderRow, error) {
	row := q.db.QueryRow(ctx, getDefaultAiProvider)
	var i GetDefaultAiProviderRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.BaseUrl,
		&i.DefaultModel,
		&i.TextModel,
		&i.VisionModel,
		&i.AudioModel,
		&i.EmbeddingModel,
		&i.EmbeddingDimensions,
		&i.IsActive,
		&i.Priority,
		&i.IsDefault,
		&i.LimitPerMinute,
		&i.LimitPerDay,
		&i.CostPerCredit,
	)
	return i, err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, description, is_public, updated_at
FROM system_settings
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.IsPublic,
		&i.UpdatedAt,
	)
	return i, err
}

const initializeCreditBalance = `-- name: InitializeCreditBalance :one
INSERT INTO ai_credit_balances (organization_id, balance)
VALUES ($1, $2)
ON CONFLICT (organization_id) DO NOTHING
RETURNING id, organization_id, balance, updated_at
`

type InitializeCreditBalanceParams struct {
	OrganizationID pgtype.UUID
	Balance        int32
}

func (q *Queries) InitializeCreditBalance(ctx context.Context, arg InitializeCreditBalanceParams) (AiCreditBalance, error) {
	row := q.db.QueryRow(ctx, initializeCreditBalance, arg.OrganizationID, arg.Balance)
	var i AiCreditBalance
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Balance,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT key, value, description, is_public, updated_at
FROM system_settings
ORDER BY key ASC
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.IsPublic,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreditBalance = `-- name: UpdateCreditBalance :one
UPDATE ai_credit_balances
SET balance = balance + $2
WHERE organization_id = $1
RETURNING id, organization_id, balance, updated_at
`

type UpdateCreditBalanceParams struct {
	OrganizationID pgtype.UUID
	Balance        int32
}

func (q *Queries) UpdateCreditBalance(ctx context.Context, arg UpdateCreditBalanceParams) (AiCreditBalance, error) {
	row := q.db.QueryRow(ctx, updateCreditBalance, arg.OrganizationID, arg.Balance)
	var i AiCreditBalance
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Balance,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (key, value, description, is_public)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    description = COALESCE(EXCLUDED.description, system_settings.description),
    is_public = EXCLUDED.is_public,
    updated_at = NOW()
RETURNING key, value, description, is_public, updated_at
`

type UpsertSystemSettingParams struct {
	Key         string
	Value       json.RawMessage
	Description pgtype.Text
	IsPublic    bool
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting,
		arg.Key,
		arg.Value,
		arg.Description,
		arg.IsPublic,
	)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.IsPublic,
		&i.UpdatedAt,
	)
	return i, err
}
