// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCreditTransactionsByOrganization = `-- name: CountCreditTransactionsByOrganization :one
SELECT COUNT(*) FROM ai_credit_transactions
WHERE organization_id = $1
  AND ($2::text IS NULL OR type = $2)
`

type CountCreditTransactionsByOrganizationParams struct {
	OrganizationID pgtype.UUID
	Type           pgtype.Text
}

func (q *Queries) CountCreditTransactionsByOrganization(ctx context.Context, arg CountCreditTransactionsByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCreditTransactionsByOrganization, arg.OrganizationID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAiActionPrice = `-- name: CreateAiActionPrice :one
INSERT INTO ai_action_prices (action_key, name, description, credits_cost, is_active, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, action_key, name, description, credits_cost, is_active, metadata, created_at, updated_at
`

type CreateAiActionPriceParams struct {
	ActionKey   string
	Name        string
	Description pgtype.Text
	CreditsCost int32
	IsActive    bool
	Metadata    []byte
}

func (q *Queries) CreateAiActionPrice(ctx context.Context, arg CreateAiActionPriceParams) (AiActionPrice, error) {
	row := q.db.QueryRow(ctx, createAiActionPrice,
		arg.ActionKey,
		arg.Name,
		arg.Description,
		arg.CreditsCost,
		arg.IsActive,
		arg.Metadata,
	)
	var i AiActionPrice
	err := row.Scan(
		&i.ID,
		&i.ActionKey,
		&i.Name,
		&i.Description,
		&i.CreditsCost,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAiProvider = `-- name: CreateAiProvider :one
INSERT INTO ai_providers (
    name, slug, api_key_secure, base_url, default_model, text_model,
    vision_model, audio_model, embedding_model, embedding_dimensions,
    is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, name, slug, api_key_secure, base_url, default_model, text_model, vision_model, audio_model, embedding_model, embedding_dimensions, is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit, created_at, updated_at
`

type CreateAiProviderParams struct {
	Name                string
	Slug                string
	ApiKeySecure        string
	BaseUrl             pgtype.Text
	DefaultModel        string
	TextModel           string
	VisionModel         string
	AudioModel          string
	EmbeddingModel      string
	EmbeddingDimensions int32
	IsActive            bool
	Priority            int32
	IsDefault           bool
	LimitPerMinute      int32
	LimitPerDay         int32
	CostPerCredit       pgtype.Numeric
}

func (q *Queries) CreateAiProvider(ctx context.Context, arg CreateAiProviderParams) (AiProvider, error) {
	row := q.db.QueryRow(ctx, createAiProvider,
		arg.Name,
		arg.Slug,
		arg.ApiKeySecure,
		arg.BaseUrl,
		arg.DefaultModel,
		arg.TextModel,
		arg.VisionModel,
		arg.AudioModel,
		arg.EmbeddingModel,
		arg.EmbeddingDimensions,
		arg.IsActive,
		arg.Priority,
		arg.IsDefault,
		arg.LimitPerMinute,
		arg.LimitPerDay,
		arg.CostPerCredit,
	)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.BaseUrl,
		&i.DefaultModel,
		&i.TextModel,
		&i.VisionModel,
		&i.AudioModel,
		&i.EmbeddingModel,
		&i.EmbeddingDimensions,
		&i.IsActive,
		&i.Priority,
		&i.IsDefault,
		&i.LimitPerMinute,
		&i.LimitPerDay,
		&i.CostPerCredit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCreditTransaction = `-- name: CreateCreditTransaction :one
INSERT INTO ai_credit_transactions (organization_id, amount, type, description, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, amount, type, description, metadata, created_at
`

type CreateCreditTransactionParams struct {
	OrganizationID pgtype.UUID
	Amount         int32
	Type           string
	Description    string
	Metadata       []byte
}

func (q *Queries) CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (AiCreditTransaction, error) {
	row := q.db.QueryRow(ctx, createCreditTransaction,
		arg.OrganizationID,
		arg.Amount,
		arg.Type,
		arg.Description,
		arg.Metadata,
	)
	var i AiCreditTransaction
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAiActionPrice = `-- name: GetAiActionPrice :one
SELECT id, action_key, name, description, credits_cost, is_active, metadata, created_at, updated_at
FROM ai_action_prices
WHERE action_key = $1 LIMIT 1
`

func (q *Queries) GetAiActionPrice(ctx context.Context, actionKey string) (AiActionPrice, error) {
	row := q.db.QueryRow(ctx, getAiActionPrice, actionKey)
	var i AiActionPrice
	err := row.Scan(
		&i.ID,
		&i.ActionKey,
		&i.Name,
		&i.Description,
		&i.CreditsCost,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAiProviderByID = `-- name: GetAiProviderByID :one
SELECT id, name, slug, api_key_secure, base_url, default_model, text_model, vision_model, audio_model, embedding_model, embedding_dimensions, is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit, created_at, updated_at
FROM ai_providers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAiProviderByID(ctx context.Context, id pgtype.UUID) (AiProvider, error) {
	row := q.db.QueryRow(ctx, getAiProviderByID, id)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.BaseUrl,
		&i.DefaultModel,
		&i.TextModel,
		&i.VisionModel,
		&i.AudioModel,
		&i.EmbeddingModel,
		&i.EmbeddingDimensions,
		&i.IsActive,
		&i.Priority,
		&i.IsDefault,
		&i.LimitPerMinute,
		&i.LimitPerDay,
		&i.CostPerCredit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAiProviderBySlug = `-- name: GetAiProviderBySlug :one
SELECT id, name, slug, api_key_secure, base_url, default_model, text_model, vision_model, audio_model, embedding_model, embedding_dimensions, is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit, created_at, updated_at
FROM ai_providers
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetAiProviderBySlug(ctx context.Context, slug string) (AiProvider, error) {
	row := q.db.QueryRow(ctx, getAiProviderBySlug, slug)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.BaseUrl,
		&i.DefaultModel,
		&i.TextModel,
		&i.VisionModel,
		&i.AudioModel,
		&i.EmbeddingModel,
		&i.EmbeddingDimensions,
		&i.IsActive,
		&i.Priority,
		&i.IsDefault,
		&i.LimitPerMinute,
		&i.LimitPerDay,
		&i.CostPerCredit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditBalance = `-- name: GetCreditBalance :one
SELECT id, organization_id, balance, updated_at
FROM ai_credit_balances
WHERE organization_id = $1 LIMIT 1
`

func (q *Queries) GetCreditBalance(ctx context.Context, organizationID pgtype.UUID) (AiCreditBalance, error) {
	row := q.db.QueryRow(ctx, getCreditBalance, organizationID)
	var i AiCreditBalance
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Balance,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultAiProvider = `-- name: GetDefaultAiProvider :one
SELECT id, name, slug, api_key_secure, base_url, default_model, text_model, vision_model, audio_model, embedding_model, embedding_dimensions, is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit
FROM ai_providers
WHERE is_active = TRUE AND is_default = TRUE LIMIT 1
`

type GetDefaultAiProviderRow struct {
	ID                  pgtype.UUID
	Name                string
	Slug                string
	ApiKeySecure        string
	BaseUrl             pgtype.Text
	DefaultModel        string
	TextModel           string
	VisionModel         string
	AudioModel          string
	EmbeddingModel      string
	EmbeddingDimensions int32
	IsActive            bool
	Priority            int32
	IsDefault           bool
	LimitPerMinute      int32
	LimitPerDay         int32
	CostPerCredit       pgtype.Numeric
}

func (q *Queries) GetDefaultAiProvider(ctx context.Context) (GetDefaultAiProviderRow, error) {
	row := q.db.QueryRow(ctx, getDefaultAiProvider)
	var i GetDefaultAiProviderRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.BaseUrl,
		&i.DefaultModel,
		&i.TextModel,
		&i.VisionModel,
		&i.AudioModel,
		&i.EmbeddingModel,
		&i.EmbeddingDimensions,
		&i.IsActive,
		&i.Priority,
		&i.IsDefault,
		&i.LimitPerMinute,
		&i.LimitPerDay,
		&i.CostPerCredit,
	)
	return i, err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, description, is_public, updated_at
FROM system_settings
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.IsPublic,
		&i.UpdatedAt,
	)
	return i, err
}

const initializeCreditBalance = `-- name: InitializeCreditBalance :one
INSERT INTO ai_credit_balances (organization_id, balance)
VALUES ($1, $2)
ON CONFLICT (organization_id) DO NOTHING
RETURNING id, organization_id, balance, updated_at
`

type InitializeCreditBalanceParams struct {
	OrganizationID pgtype.UUID
	Balance        int32
}

func (q *Queries) InitializeCreditBalance(ctx context.Context, arg InitializeCreditBalanceParams) (AiCreditBalance, error) {
	row := q.db.QueryRow(ctx, initializeCreditBalance, arg.OrganizationID, arg.Balance)
	var i AiCreditBalance
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Balance,
		&i.UpdatedAt,
	)
	return i, err
}

const listAiActionPrices = `-- name: ListAiActionPrices :many
SELECT id, action_key, name, description, credits_cost, is_active, metadata, created_at, updated_at
FROM ai_action_prices
ORDER BY action_key ASC
`

func (q *Queries) ListAiActionPrices(ctx context.Context) ([]AiActionPrice, error) {
	rows, err := q.db.Query(ctx, listAiActionPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiActionPrice
	for rows.Next() {
		var i AiActionPrice
		if err := rows.Scan(
			&i.ID,
			&i.ActionKey,
			&i.Name,
			&i.Description,
			&i.CreditsCost,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAiProviders = `-- name: ListAiProviders :many
SELECT id, name, slug, api_key_secure, base_url, default_model, text_model, vision_model, audio_model, embedding_model, embedding_dimensions, is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit, created_at, updated_at
FROM ai_providers
ORDER BY priority DESC, name ASC
`

func (q *Queries) ListAiProviders(ctx context.Context) ([]AiProvider, error) {
	rows, err := q.db.Query(ctx, listAiProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiProvider
	for rows.Next() {
		var i AiProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ApiKeySecure,
			&i.BaseUrl,
			&i.DefaultModel,
			&i.TextModel,
			&i.VisionModel,
			&i.AudioModel,
			&i.EmbeddingModel,
			&i.EmbeddingDimensions,
			&i.IsActive,
			&i.Priority,
			&i.IsDefault,
			&i.LimitPerMinute,
			&i.LimitPerDay,
			&i.CostPerCredit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditTransactionsByOrganization = `-- name: ListCreditTransactionsByOrganization :many
SELECT id, organization_id, amount, type, description, metadata, created_at
FROM ai_credit_transactions
WHERE organization_id = $1
  AND ($4::text IS NULL OR type = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCreditTransactionsByOrganizationParams struct {
	OrganizationID pgtype.UUID
	Limit          int32
	Offset         int32
	Type           pgtype.Text
}

func (q *Queries) ListCreditTransactionsByOrganization(ctx context.Context, arg ListCreditTransactionsByOrganizationParams) ([]AiCreditTransaction, error) {
	rows, err := q.db.Query(ctx, listCreditTransactionsByOrganization,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.Type,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiCreditTransaction
	for rows.Next() {
		var i AiCreditTransaction
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT key, value, description, is_public, updated_at
FROM system_settings
ORDER BY key ASC
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.IsPublic,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAiProviderDefault = `-- name: SetAiProviderDefault :exec
UPDATE ai_providers
SET is_default = TRUE
WHERE id = $1
`

func (q *Queries) SetAiProviderDefault(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setAiProviderDefault, id)
	return err
}

const setAllAiProvidersNotDefault = `-- name: SetAllAiProvidersNotDefault :exec
UPDATE ai_providers
SET is_default = FALSE
`

func (q *Queries) SetAllAiProvidersNotDefault(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setAllAiProvidersNotDefault)
	return err
}

const updateAiActionPrice = `-- name: UpdateAiActionPrice :one
UPDATE ai_action_prices
SET credits_cost = $2,
    is_active = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, action_key, name, description, credits_cost, is_active, metadata, created_at, updated_at
`

type UpdateAiActionPriceParams struct {
	ID          pgtype.UUID
	CreditsCost int32
	IsActive    bool
}

func (q *Queries) UpdateAiActionPrice(ctx context.Context, arg UpdateAiActionPriceParams) (AiActionPrice, error) {
	row := q.db.QueryRow(ctx, updateAiActionPrice, arg.ID, arg.CreditsCost, arg.IsActive)
	var i AiActionPrice
	err := row.Scan(
		&i.ID,
		&i.ActionKey,
		&i.Name,
		&i.Description,
		&i.CreditsCost,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAiProvider = `-- name: UpdateAiProvider :one
UPDATE ai_providers
SET name = COALESCE($2, name),
    api_key_secure = COALESCE($3, api_key_secure),
    base_url = COALESCE($4, base_url),
    default_model = COALESCE($5, default_model),
    text_model = COALESCE($6, text_model),
    vision_model = COALESCE($7, vision_model),
    audio_model = COALESCE($8, audio_model),
    embedding_model = COALESCE($9, embedding_model),
    embedding_dimensions = COALESCE($10, embedding_dimensions),
    is_active = COALESCE($11, is_active),
    priority = COALESCE($12, priority),
    is_default = COALESCE($13, is_default),
    limit_per_minute = COALESCE($14, limit_per_minute),
    limit_per_day = COALESCE($15, limit_per_day),
    cost_per_credit = COALESCE($16, cost_per_credit),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, api_key_secure, base_url, default_model, text_model, vision_model, audio_model, embedding_model, embedding_dimensions, is_active, priority, is_default, limit_per_minute, limit_per_day, cost_per_credit, created_at, updated_at
`

type UpdateAiProviderParams struct {
	ID                  pgtype.UUID
	Name                string
	ApiKeySecure        string
	BaseUrl             pgtype.Text
	DefaultModel        string
	TextModel           string
	VisionModel         string
	AudioModel          string
	EmbeddingModel      string
	EmbeddingDimensions int32
	IsActive            bool
	Priority            int32
	IsDefault           bool
	LimitPerMinute      int32
	LimitPerDay         int32
	CostPerCredit       pgtype.Numeric
}

func (q *Queries) UpdateAiProvider(ctx context.Context, arg UpdateAiProviderParams) (AiProvider, error) {
	row := q.db.QueryRow(ctx, updateAiProvider,
		arg.ID,
		arg.Name,
		arg.ApiKeySecure,
		arg.BaseUrl,
		arg.DefaultModel,
		arg.TextModel,
		arg.VisionModel,
		arg.AudioModel,
		arg.EmbeddingModel,
		arg.EmbeddingDimensions,
		arg.IsActive,
		arg.Priority,
		arg.IsDefault,
		arg.LimitPerMinute,
		arg.LimitPerDay,
		arg.CostPerCredit,
	)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ApiKeySecure,
		&i.BaseUrl,
		&i.DefaultModel,
		&i.TextModel,
		&i.VisionModel,
		&i.AudioModel,
		&i.EmbeddingModel,
		&i.EmbeddingDimensions,
		&i.IsActive,
		&i.Priority,
		&i.IsDefault,
		&i.LimitPerMinute,
		&i.LimitPerDay,
		&i.CostPerCredit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCreditBalance = `-- name: UpdateCreditBalance :one
UPDATE ai_credit_balances
SET balance = balance + $2
WHERE organization_id = $1
RETURNING id, organization_id, balance, updated_at
`

type UpdateCreditBalanceParams struct {
	OrganizationID pgtype.UUID
	Balance        int32
}

func (q *Queries) UpdateCreditBalance(ctx context.Context, arg UpdateCreditBalanceParams) (AiCreditBalance, error) {
	row := q.db.QueryRow(ctx, updateCreditBalance, arg.OrganizationID, arg.Balance)
	var i AiCreditBalance
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Balance,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (key, value, description, is_public)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    description = COALESCE(EXCLUDED.description, system_settings.description),
    is_public = EXCLUDED.is_public,
    updated_at = NOW()
RETURNING key, value, description, is_public, updated_at
`

type UpsertSystemSettingParams struct {
	Key         string
	Value       json.RawMessage
	Description pgtype.Text
	IsPublic    bool
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting,
		arg.Key,
		arg.Value,
		arg.Description,
		arg.IsPublic,
	)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.IsPublic,
		&i.UpdatedAt,
	)
	return i, err
}
