// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUploadsByOrganization = `-- name: CountUploadsByOrganization :one
SELECT COUNT(*) FROM uploads WHERE organization_id = $1 AND status != 'FAILED'
`

func (q *Queries) CountUploadsByOrganization(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUploadsByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (
    organization_id, user_id, filename, original_name, mime_type, size, storage_provider, storage_key, status, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, user_id, filename, original_name, mime_type, size, storage_provider, storage_key, status, metadata, created_at, updated_at
`

type CreateUploadParams struct {
	OrganizationID  pgtype.UUID
	UserID          pgtype.UUID
	Filename        string
	OriginalName    string
	MimeType        string
	Size            int64
	StorageProvider string
	StorageKey      string
	Status          string
	Metadata        []byte
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.OrganizationID,
		arg.UserID,
		arg.Filename,
		arg.OriginalName,
		arg.MimeType,
		arg.Size,
		arg.StorageProvider,
		arg.StorageKey,
		arg.Status,
		arg.Metadata,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.Size,
		&i.StorageProvider,
		&i.StorageKey,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadByID = `-- name: GetUploadByID :one
SELECT id, organization_id, user_id, filename, original_name, mime_type, size, storage_provider, storage_key, status, metadata, created_at, updated_at
FROM uploads
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUploadByID(ctx context.Context, id pgtype.UUID) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadByID, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.Size,
		&i.StorageProvider,
		&i.StorageKey,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUploadsByOrganization = `-- name: ListUploadsByOrganization :many
SELECT id, organization_id, user_id, filename, original_name, mime_type, size, storage_provider, storage_key, status, metadata, created_at
FROM uploads
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUploadsByOrganizationParams struct {
	OrganizationID pgtype.UUID
	Limit          int32
	Offset         int32
}

type ListUploadsByOrganizationRow struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	UserID          pgtype.UUID
	Filename        string
	OriginalName    string
	MimeType        string
	Size            int64
	StorageProvider string
	StorageKey      string
	Status          string
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListUploadsByOrganization(ctx context.Context, arg ListUploadsByOrganizationParams) ([]ListUploadsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listUploadsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUploadsByOrganizationRow
	for rows.Next() {
		var i ListUploadsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.Size,
			&i.StorageProvider,
			&i.StorageKey,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUploadSizeByOrganization = `-- name: SumUploadSizeByOrganization :one
SELECT COALESCE(SUM(size), 0)::bigint FROM uploads WHERE organization_id = $1 AND status != 'FAILED'
`

func (q *Queries) SumUploadSizeByOrganization(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumUploadSizeByOrganization, organizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateUploadStatus = `-- name: UpdateUploadStatus :one
UPDATE uploads
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, status, updated_at
`

type UpdateUploadStatusParams struct {
	ID     pgtype.UUID
	Status string
}

type UpdateUploadStatusRow struct {
	ID        pgtype.UUID
	Status    string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUploadStatus(ctx context.Context, arg UpdateUploadStatusParams) (UpdateUploadStatusRow, error) {
	row := q.db.QueryRow(ctx, updateUploadStatus, arg.ID, arg.Status)
	var i UpdateUploadStatusRow
	err := row.Scan(&i.ID, &i.Status, &i.UpdatedAt)
	return i, err
}
