export interface AINode {
  id: string;
  parentId: string | null;
  title: string;
  content: string;
  level: number;
  order: number;
  position?: { x: number; y: number };
  collapsed?: boolean;
  style?: { color?: string | null; icon?: string | null };
}

export interface AIEdge {
  id?: string;
  source: string;
  target: string;
}

export interface MindMapData {
  title: string;
  centralTopic: string;
  summary: string;
  nodes: AINode[];
  edges: AIEdge[];
  viewport?: { x: number; y: number; zoom: number };
}

// Normalizes mind map data generated by IA or older templates
export function normalizeMindMapData(raw: any): MindMapData {
  const title = raw.title || '';
  const centralTopic = raw.centralTopic || '';
  const summary = raw.summary || '';
  const nodes = (raw.nodes || []).map((n: any) => ({
    ...n,
    parentId: n.parentId || null,
    level: n.level ?? 0,
    order: n.order ?? 0,
    collapsed: n.collapsed ?? false,
    style: n.style || {},
  }));

  const edges = (raw.edges || []).map((e: any) => ({
    ...e,
    id: e.id || `edge-${e.source}-${e.target}`,
  }));

  const viewport = raw.viewport || { x: 0, y: 0, zoom: 1 };

  return {
    title,
    centralTopic,
    summary,
    nodes,
    edges,
    viewport,
  };
}

// Gets descendant node IDs recursively
export function getDescendantIds(nodeId: string, nodes: AINode[]): string[] {
  const descendants: string[] = [];
  const findChildren = (id: string) => {
    const children = nodes.filter((n) => n.parentId === id);
    children.forEach((c) => {
      descendants.push(c.id);
      findChildren(c.id);
    });
  };
  findChildren(nodeId);
  return descendants;
}

// Counts descendants of a node
export function countDescendants(nodeId: string, nodes: AINode[]): number {
  return getDescendantIds(nodeId, nodes).length;
}

// Removes a node and its descendants recursively
export function removeSubtree(
  nodeId: string,
  nodes: AINode[],
  edges: AIEdge[]
): { nodes: AINode[]; edges: AIEdge[] } {
  const idsToRemove = [nodeId, ...getDescendantIds(nodeId, nodes)];
  
  const filteredNodes = nodes.filter((n) => !idsToRemove.includes(n.id));
  const filteredEdges = edges.filter(
    (e) => !idsToRemove.includes(e.source) && !idsToRemove.includes(e.target)
  );

  return {
    nodes: filteredNodes,
    edges: filteredEdges,
  };
}
